# docker-compose.yml
version: '3.8'

services:
  # ---------- MINIO ----------
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    volumes:
      - minio_/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # ---------- POSTGRESQL ----------
  db:
    image: postgres:15
    container_name: postgres_ged
    volumes:
      - postgres_/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: secure_doc
      POSTGRES_USER: secure_doc
      POSTGRES_PASSWORD: secure_doc_pass
    ports:
      - "5432:5432"

  # ---------- DJANGO ----------
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django_ged
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here-change-in-prod
      - DATABASE_URL=postgresql://secure_doc:secure_doc_pass@db:5432/secure_doc
      # MinIO config
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_STORAGE_BUCKET_NAME=secure-docs
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_REGION_NAME=us-east-1
      - AWS_S3_USE_SSL=False
      - AWS_S3_VERIFY=False
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # ---------- (Optionnel) NGINX ----------
  # nginx:
  #   build: ./docker/nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - django
  #   volumes:
  #     - static_volume:/app/staticfiles

volumes:
  postgres_data:
  minio_data:
  # static_volume: